# Generated by Django 2.2.5 on 2019-10-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.CharField(blank=True, help_text='Описание чата может быть максимум в 1023 символов', max_length=1023, null=True, verbose_name='Описание чата'),
        ),
    ]
