# Generated by Django 2.2.5 on 2019-10-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20191015_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='notifications',
        ),
        migrations.AddField(
            model_name='membership',
            name='notifications',
            field=models.BooleanField(default=True, help_text='Будут ли появляться на телефоне нотификации о сообщении', verbose_name='Присылать ли нотификации'),
        ),
    ]
