# Generated by Django 2.2.5 on 2019-11-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20191026_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-date_started']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_created'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
