# Generated by Django 2.2.5 on 2019-11-28 10:11

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название картинки может быть максимум в 255 символов',
                                          max_length=255, verbose_name='Название картинки')),
                ('imageURL', models.CharField(max_length=100, verbose_name='Image URL')),
                ('imageFile', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ImageFile')),
                ('object_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинка',
                'db_table': 'Picture',
                'ordering': ['-date_created'],
            },
        ),
    ]
